#!/bin/bash
# yl1 - väljastab 5 rida, igas 5 tärni (sisseehitatud for-tsüklid)
for (( i=1; i<=5; i++ )); do
    echo -n "$i. "
    for (( j=1; j<=5; j++ )); do
        echo -n "* "
    done
    echo ""
done
