#!/bin/bash
# yl1 - arvutab paarisarvude summa vahemikus 1 kuni 10 (for-tsükliga)
summa=0
for (( i=1; i<=10; i++ )); do
    if (( i % 2 == 0 )); then
        summa=$(( summa + i ))
    fi
done
echo "Arvude vahemikus 1 kuni 10 (kaasaarvatud) paarisarvude summa on: $summa"
