#!/bin/bash
# Skript väljastab praeguse kuupäeva, kellaaja ja käesoleva kuu kalendri

echo -n "Today is "
date +"%A, %B %d, %Y"

date +"Time is %H:%M"
echo ""

date +"Calendar of %B %Y"
cal | tail -n 7
